"""Create entity tables, vector store, and ingestion log

Revision ID: 930864a558eb
Revises: 0fcacbc15356
Create Date: 2026-05-15 20:30:32.852931

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector  # noqa: F401 — required for VECTOR column type
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930864a558eb'
down_revision: Union[str, None] = '0fcacbc15356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('article_reference', sa.Text(), nullable=True),
    sa.Column('parent_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('ingestion_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_vintage', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingestion_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_removed', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_vintage', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanctioned_entities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('primary_name', sa.Text(), nullable=False),
    sa.Column('programs', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('legal_basis', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('country_of_registration', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('data_vintage', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_record', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_sanctioned_entities_source_source_id')
    )
    op.create_table('entity_addresses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('alias_name', sa.Text(), nullable=False),
    sa.Column('alias_type', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_identifiers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('id_type', sa.Text(), nullable=False),
    sa.Column('id_value', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('ownership_percentage', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_entity_id', 'to_entity_id', 'relationship_type', name='uq_entity_relationships_from_to_type')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('vessel_name', sa.Text(), nullable=True),
    sa.Column('imo_number', sa.Text(), nullable=True),
    sa.Column('mmsi_number', sa.Text(), nullable=True),
    sa.Column('vessel_type', sa.Text(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.Column('tonnage', sa.Text(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('call_sign', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['sanctioned_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Manual: HNSW index for vector similarity search
    op.execute("""
        CREATE INDEX ix_document_chunks_embedding_hnsw
        ON document_chunks USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)

    # Manual: full-text search generated column + GIN index
    op.execute("""
        ALTER TABLE document_chunks ADD COLUMN tsv tsvector
        GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
    """)
    op.execute("""
        CREATE INDEX ix_document_chunks_tsv_gin
        ON document_chunks USING gin (tsv)
    """)

    # Manual: trigram indexes for fuzzy name matching
    op.execute("""
        CREATE INDEX ix_sanctioned_entities_primary_name_trgm
        ON sanctioned_entities USING gin (primary_name gin_trgm_ops)
    """)
    op.execute("""
        CREATE INDEX ix_entity_aliases_alias_name_trgm
        ON entity_aliases USING gin (alias_name gin_trgm_ops)
    """)


def downgrade() -> None:
    # Manual: drop indexes and generated column
    op.execute("DROP INDEX IF EXISTS ix_entity_aliases_alias_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_sanctioned_entities_primary_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_tsv_gin")
    op.execute("ALTER TABLE document_chunks DROP COLUMN IF EXISTS tsv")
    op.execute("DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessels')
    op.drop_table('entity_relationships')
    op.drop_table('entity_identifiers')
    op.drop_table('entity_aliases')
    op.drop_table('entity_addresses')
    op.drop_table('sanctioned_entities')
    op.drop_table('ingestion_log')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
